### ISSUE TITLE
Feature Request: Enhance UI and Add Edit Functionality

### ISSUE THREAD

**Issue by Vimal-Mudalagi** [Mahir-Neema/minimilisitc_todo_app#1]
## Feature Request: Enhance UI and Add Edit Functionality

Hi Mahir,

I hope this message finds you well! I came across your **todo app** on GitHub, and I think it’s a great project. 

I noticed that the **UI** could be enhanced to make it more visually appealing, and I would love to add an **edit option** to improve user experience. As an intermediate **ReactJS developer**, I'm eager to contribute and help make this project even better.

Would it be okay for me to work on these features? I would appreciate any guidance or suggestions you might have!

Thank you for your time!

Best,
Vimal Mudalagi

**Comment by Mahir-Neema** [comment]
Sure vimal, go ahead raise a PR, will review it on this weekend.

**Comment by Vimal-Mudalagi** [comment]
Thank you so much for the opportunity!
I’ll start working on the features and will raise a PR soon. I appreciate your willingness to review it this weekend!

Looking forward to your feedback!

**Comment by Vimal-Mudalagi** [comment]
Hey Mahir,
Just wanted to remind you about the PR I sent a few days ago. Let me know if you need anything from my side.

**Comment by Mahir-Neema** [comment]
Merged :)
The only issue is that the theme toggle is translating while hovering, which looks unrefined.

**Comment by Vimal-Mudalagi** [comment]
thanks.I designed the theme toggle to have the hover effect for a bit of animation.
